name: benchmarks

on: workflow_dispatch

env:
  MATURIN_VERSION: 0.12.12

jobs:
  benchmarks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: messense/maturin-action@v1
      with:
        maturin-version: v${{ env.MATURIN_VERSION }}
        command: build
        args: --release --strip --no-sdist --interpreter python3.9
        target: x64
        manylinux: auto
        container: off
    - name: Deps
      run: |
        pip install target/wheels/granian-0.1.0-cp39-cp39-manylinux_2_28_x86_64.whl
        pip install uvicorn==0.17.6
        pip install httptools
    - name: wrk
      run: |
        git clone https://github.com/wg/wrk.git .wrk
        cd .wrk && make && sudo mv wrk /usr/local/bin
    - name: Benchmarks
      run: |
        cd benchmarks && python benchmarks.py
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: benchmarks/results/*
