name: release

on:
  release:
    types: [published]

env:
  MATURIN_VERSION: 0.14.10

jobs:
  sdist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: pyo3/maturin-action@v1
      with:
        maturin-version: v${{ env.MATURIN_VERSION }}
        command: build
        args: --release --sdist --interpreter python${{ matrix.python-config.version }}
        target: x64
        manylinux: off
        container: off
    - name: Upload sdist
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels/*.tar.gz

  linux-gnu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-config:
          - version: 3.7
            lib: cp37-cp37m
          - version: 3.8
            lib: cp38-cp38
          - version: 3.9
            lib: cp39-cp39
          - version: '3.10'
            lib: cp310-cp310
          - version: '3.11'
            lib: cp311-cp311
        target:
          - arch: x86_64
          - arch: aarch64

    steps:
    - uses: actions/checkout@v2
    - uses: pyo3/maturin-action@v1
      env:
        PYO3_CROSS_PYTHON_VERSION: '${{ matrix.python-config.version }}'
        PYO3_CROSS_LIB_DIR: /opt/python/${{ matrix.python-config.lib }}/lib
      with:
        maturin-version: v${{ env.MATURIN_VERSION }}
        command: build
        args: --release --interpreter python${{ matrix.python-config.version }}
        target: ${{ matrix.target.arch }}
        manylinux: auto
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels

  linux-gnu-pypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pypy:
          - pypy3.7
          - pypy3.8
          - pypy3.9

    steps:
    - uses: actions/checkout@v2
    - uses: pyo3/maturin-action@v1
      with:
        maturin-version: v${{ env.MATURIN_VERSION }}
        command: build
        args: --release --interpreter ${{ matrix.pypy }}
        target: x86_64
        manylinux: auto
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels

  linux-musl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-config:
          - version: 3.7
            lib: cp37-cp37m
          - version: 3.8
            lib: cp38-cp38
          - version: 3.9
            lib: cp39-cp39
          - version: '3.10'
            lib: cp310-cp310
          - version: '3.11'
            lib: cp311-cp311
        target:
          - arch: x86_64
          - arch: aarch64

    steps:
    - uses: actions/checkout@v2
    - uses: pyo3/maturin-action@v1
      env:
        PYO3_CROSS_PYTHON_VERSION: '${{ matrix.python-config.version }}'
        PYO3_CROSS_LIB_DIR: /opt/python/${{ matrix.python-config.lib }}/lib
      with:
        maturin-version: v${{ env.MATURIN_VERSION }}
        command: build
        args: --release --interpreter python${{ matrix.python-config.version }}
        target: ${{ matrix.target.arch }}
        manylinux: musllinux_1_1
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-config:
          - version: 3.7
            interpreter: python3.7
          - version: 3.8
            interpreter: python3.8
          - version: 3.9
            interpreter: python3.9
          - version: '3.10'
            interpreter: python3.10
          - version: '3.11'
            interpreter: python3.11
          - version: 'pypy3.9'
            interpreter: pypy

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-config.version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-config.version }}
    - uses: pyo3/maturin-action@v1
      with:
        maturin-version: v${{ env.MATURIN_VERSION }}
        command: build
        args: --release --interpreter ${{ matrix.python-config.interpreter }}
        target: x86_64
    - uses: pyo3/maturin-action@v1
      with:
        maturin-version: v${{ env.MATURIN_VERSION }}
        command: build
        args: --release --universal2 --interpreter ${{ matrix.python-config.interpreter }}
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11', 'pypy3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: pyo3/maturin-action@v1
      with:
        maturin-version: v${{ env.MATURIN_VERSION }}
        command: build
        args: --release
        target: x86_64
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels

  release:
    runs-on: ubuntu-latest
    needs: [ sdist, linux-gnu, linux-musl, macos, windows ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install --upgrade pip twine
          twine upload --skip-existing *
